// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWa8V2i3lv9qgC98QyI3ggZ50jYxpg9k4',
    appId: '1:81081966482:web:44da6dcb40f5467df86b4b',
    messagingSenderId: '81081966482',
    projectId: 'mobileprogramming-5d96e',
    authDomain: 'mobileprogramming-5d96e.firebaseapp.com',
    storageBucket: 'mobileprogramming-5d96e.firebasestorage.app',
    measurementId: 'G-P8080W1YSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY8YKj71PBm2LXeMsAlNGlYXxjBM-8Lck',
    appId: '1:81081966482:android:d6d741aacbfcabb3f86b4b',
    messagingSenderId: '81081966482',
    projectId: 'mobileprogramming-5d96e',
    storageBucket: 'mobileprogramming-5d96e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhUhrjdHd-tlsajjvv0A5k4MOPZzszc7A',
    appId: '1:81081966482:ios:1f6d8b8d12a4f034f86b4b',
    messagingSenderId: '81081966482',
    projectId: 'mobileprogramming-5d96e',
    storageBucket: 'mobileprogramming-5d96e.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhUhrjdHd-tlsajjvv0A5k4MOPZzszc7A',
    appId: '1:81081966482:ios:1f6d8b8d12a4f034f86b4b',
    messagingSenderId: '81081966482',
    projectId: 'mobileprogramming-5d96e',
    storageBucket: 'mobileprogramming-5d96e.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWa8V2i3lv9qgC98QyI3ggZ50jYxpg9k4',
    appId: '1:81081966482:web:58f15df7db6d93c0f86b4b',
    messagingSenderId: '81081966482',
    projectId: 'mobileprogramming-5d96e',
    authDomain: 'mobileprogramming-5d96e.firebaseapp.com',
    storageBucket: 'mobileprogramming-5d96e.firebasestorage.app',
    measurementId: 'G-4VWDSZ93R7',
  );
}
